### ISSUE TITLE
I met a problem "[AzkabanWebServerModule] [Azkaban] Could not instantiate UserManager net.researchgate.azkaban.LdapUserManager"

### ISSUE THREAD

**Issue by sober-wang** [researchgate/azkaban-ldap-usermanager#15]
I met a problem ,in my azkaban logs it show  "[AzkabanWebServerModule] [Azkaban] Could not instantiate UserManager net.researchgate.azkaban.LdapUserManager"
I'm follow the README.md modify my azkaba-web-server config file.

2019/03/27 16:00:35.022 +0800 INFO [TriggerManager] [Azkaban] TriggerManager loaded.
2019/03/27 16:00:35.026 +0800 INFO [AzkabanWebServerModule] [Azkaban] Loading user manager class net.researchgate.azkaban.LdapUserManager
2019/03/27 16:00:35.026 +0800 ERROR [AzkabanWebServerModule] [Azkaban] Could not instantiate UserManager net.researchgate.azkaban.LdapUserManager
2019/03/27 16:00:35.094 +0800 ERROR [StdOutErrRedirect] [Azkaban] Exception in thread "main"
2019/03/27 16:00:35.099 +0800 ERROR [StdOutErrRedirect] [Azkaban] com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at azkaban.webapp.AzkabanWebServerModule.createUserManager(AzkabanWebServerModule.java:93)
  at azkaban.webapp.AzkabanWebServerModule.createUserManager(AzkabanWebServerModule.java:93)
  while locating azkaban.user.UserManager
    for the 8th parameter of azkaban.webapp.AzkabanWebServer.<init>(AzkabanWebServer.java:168)
  at azkaban.webapp.AzkabanWebServer.class(AzkabanWebServer.java:125)
  while locating azkaban.webapp.AzkabanWebServer

1 error
2019/03/27 16:00:35.099 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
2019/03/27 16:00:35.100 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
2019/03/27 16:00:35.100 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at azkaban.webapp.AzkabanWebServer.main(AzkabanWebServer.java:228)
2019/03/27 16:00:35.100 +0800 ERROR [StdOutErrRedirect] [Azkaban] Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
2019/03/27 16:00:35.100 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at azkaban.webapp.AzkabanWebServerModule.createUserManager(AzkabanWebServerModule.java:102)
2019/03/27 16:00:35.100 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at azkaban.webapp.AzkabanWebServerModule$$FastClassByGuice$$2f44d056.invoke(<generated>)
2019/03/27 16:00:35.100 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
2019/03/27 16:00:35.100 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
2019/03/27 16:00:35.100 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
2019/03/27 16:00:35.100 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
2019/03/27 16:00:35.101 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
2019/03/27 16:00:35.101 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2019/03/27 16:00:35.103 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
2019/03/27 16:00:35.103 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
2019/03/27 16:00:35.103 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
2019/03/27 16:00:35.103 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
2019/03/27 16:00:35.103 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
2019/03/27 16:00:35.104 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
2019/03/27 16:00:35.104 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
2019/03/27 16:00:35.104 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
2019/03/27 16:00:35.104 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
2019/03/27 16:00:35.104 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2019/03/27 16:00:35.104 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
2019/03/27 16:00:35.104 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
2019/03/27 16:00:35.104 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
2019/03/27 16:00:35.104 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
2019/03/27 16:00:35.105 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
2019/03/27 16:00:35.105 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	... 2 more
2019/03/27 16:00:35.105 +0800 ERROR [StdOutErrRedirect] [Azkaban] Caused by: java.lang.reflect.InvocationTargetException
2019/03/27 16:00:35.105 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2019/03/27 16:00:35.105 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2019/03/27 16:00:35.105 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2019/03/27 16:00:35.105 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
2019/03/27 16:00:35.105 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at azkaban.webapp.AzkabanWebServerModule.createUserManager(AzkabanWebServerModule.java:99)
2019/03/27 16:00:35.105 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	... 24 more
2019/03/27 16:00:35.105 +0800 ERROR [StdOutErrRedirect] [Azkaban] Caused by: azkaban.utils.UndefinedPropertyException: Missing required property 'user.manager.ldap.useSsl'
2019/03/27 16:00:35.106 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at azkaban.utils.Props.getBoolean(Props.java:512)
2019/03/27 16:00:35.106 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	at net.researchgate.azkaban.LdapUserManager.<init>(LdapUserManager.java:54)
2019/03/27 16:00:35.106 +0800 ERROR [StdOutErrRedirect] [Azkaban] 	... 29 more

**Comment by Hillkorn** [comment]
Missing required property 'user.manager.ldap.useSsl'
Did you set this?
