### ISSUE TITLE
Support for permissions/roles

### ISSUE THREAD

**Issue by hugoboos** [researchgate/azkaban-ldap-usermanager#6]
Hi,

The user manager gives to everybody who can login admin permissions. 
I would be nice if there is support to give users other roles than the admin.
Here at our company we would not like to give everybody the responsibility to become an admin.

What are your thoughts about this?

I'm willing to implement this myself and open a PR.

**Comment by bashofmann** [comment]
Sure, sounds good. Feel free to implement it :)

**Comment by hugoboos** [comment]
I've opened a PR #7. I don't work in Java that often, so feel free to give any feedback.
